version: 1.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:ap-south-1:343192457610:cluster/springboot-cluster-poc:1"
        LoadBalancerInfo:
          ContainerName: "sample-app"
          ContainerPort: "80"
        PlatformVersion: "LATEST"
